version: '2.4'
services:
  postgres-db:
    image: postgres
    #ports:
    #  - 5432:5432
    networks:
      - ztblue
    volumes:
     # Uncomment to save sql data between container restarts
     # - ./data/db:/var/lib/postgresql/data
      - ./postgres-bootstrap.sh:/docker-entrypoint-initdb.d/postgres-bootstrap.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  example-network-init-container:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    depends_on:
      - zt-edge-router
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
    env_file:
      - ./.env
    networks:
      ztblue:
        aliases:
          - zt-edge-controller-init-container
      ztred:
        aliases:
          - zt-edge-controller-init-container
    volumes:
      - zt-fs:/hanzozt
      - .:/hanzozt/network-setup
    entrypoint: 
      - "/hanzozt/scripts/run-with-zt-cli.sh"
    command: 
      - "/hanzozt/network-setup/network-setup.sh"

volumes:
  postgres-fs:
