version: '2.4'
services:
  zt-controller:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    env_file:
      - ./.env
    ports:
      - "1280:1280"
    networks:
      zt:
        aliases:
          - zt-edge-controller
    volumes:
      - zt-fs:/hanzozt
    entrypoint:
      - "/hanzozt/scripts/run-controller.sh"

  zt-edge-router:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    depends_on:
      - zt-controller
    environment:
      - ZITI_CONTROLLER_RAWNAME="${ZITI_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_CONTROLLER_RAWNAME="${ZITI_EDGE_CONTROLLER_RAWNAME}"
      - ZITI_EDGE_ROUTER_RAWNAME=zt-edge-router
      - ZITI_EDGE_ROUTER_ROLES=public
    ports:
      - "3022:3022"
    networks:
      zt:
        aliases:
          - zt-edge-router
    volumes:
      - zt-fs:/hanzozt
    entrypoint: /bin/bash
    command: "/hanzozt/scripts/run-router.sh edge"

  postgres-db:
    image: postgres
    #ports:
    #  - 5432:5432
    networks:
      - zt
    volumes:
     # Uncomment to save sql data between container restarts
     # - ./data/db:/var/lib/postgresql/data
      - ./postgres-setup.sh:/docker-entrypoint-initdb.d/postgres-setup.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  database-tunneler:
    image: 'netfoundry/zt-tunnel:latest'
    depends_on:
      - zt-edge-router
    networks:
      - zt
    volumes:
      - ./tunnel:/netfoundry
    environment:
      - NF_REG_NAME=databaseTunneler
    command:
      - host

networks:
  zt:
    driver: bridge
volumes:
  zt-fs:
